### ISSUE TITLE
Does ecapture support hook the bio_read and bio_write?

### ISSUE THREAD

**Issue by swananan** [gojue/ecapture#394]
In my case, applicaption used bio_read and bio_write instead of ssl_write and ssl_read api, so ecapture didn't work.
Is there a workaround for this? thanks.

**Comment by cfc4n** [comment]
Yes, bio_read can be supported because the key parameters of bio_read are the same as ssl_read. For example, the 2nd and 3rd parameters.

```c
int SSL_read(SSL *s, void *buf, int num)
int BIO_read(BIO *b, void *data, int dlen)
```

However, you need to manually modify the code to adapt.

https://github.com/gojue/ecapture/blob/4630ee2edd3cc32550171e3e62e6f0ebd4f9bbf6/user/module/probe_openssl.go#L316-L338

**Comment by swananan** [comment]
I have tried this, it still need to do something, usually bio_read is inside the libcrypto.so, not the libssl.so. So I have to comment the SSL_write_key, since libcrypto.so doesn't have this symbol.
