### ISSUE TITLE
BoringSSL is not supported on linux

### ISSUE THREAD

**Issue by mspublic** [gojue/ecapture#531]
**Describe the bug**
BoringSSL is not fully supported on linux. The build tools only seem to build for android and do not have offsets for linux (desktop).

**Expected behavior**
Build scripts and tools should have BoringSSL support.

**Screenshots**

**Linux Server/Android (please complete the following information):**

- OS: ubuntu-linux-22-04-02-desktop
- Arch: aarch64
- Kernel Version: 6.5.0-26-generic
- Version: a8acecee080779e1a55a1a57d62e6d682ff21661

**Additional context**
The ./utils/boringssl_non_android_offset.sh is also broken - it mostly has android code.

**Comment by cfc4n** [comment]
You need to empty the existing borlingss repository under the deps directory and re-clone the code using `boringssl_non_android_offset.sh`.

**Comment by cfc4n** [comment]
ping? @mspublic

**Comment by mspublic** [comment]
Even with that it’s looking for android versions - not base Linux. The script needs to be modified to point to a specific commit it seems.

**Comment by cfc4n** [comment]
The current difficulty is that there are no feature identifiers in the libssl.so dynamic link library to distinguish between versions. It's not just about being unable to differentiate between Linux and Android.

but even on Android, it's impossible to distinguish the version of BoringSSL. Therefore, the current method for distinguishing BoringSSL versions is by selecting corresponding offsets based on the Android version, rather than using the `VersionNumber` string in OpenSSL.
